example/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listings.urls')),
]

listings/urls.py
from django.urls import path
from .import views

app_name = "listings"

urlpatterns = [
    path('', views.index, name="index"),
    path('greetings', views.greetings,name="greetings"),
    path('all_listings', views.all_listings, name="all_listings"),
    path('new_listing/', views.new_listing, name="new_listing"),
    path('all_listings/<int:detail_id>', views.details, name="detail")
]

listings/models.py
from django.db import models
from django.utils.timezone import now
from datetime import datetime

# Create your models here.
class Listing(models.Model):
    
    class SaleType(models.TextChoices):
        PICK_UP = "Available for pickup"
        SHIP = "Available for shipping"

    class ConditionType(models.TextChoices):
        USED = "Used"
        NEW = "New"

    class ProductType(models.TextChoices):
        BIKE = "Bike"
        PARTS = "Parts"
        MODELS = "Models"
        OTHER = "Other"
        
    title = models.CharField(max_length=100)
    condition = models.CharField(max_length=50, choices=ConditionType.choices, default=ConditionType.USED)
    product_type = models.CharField(max_length=50, choices=ProductType.choices, default=ProductType.BIKE)
    sale_type = models.CharField(max_length=50, choices=SaleType.choices, default=SaleType.SHIP)
    price = models.FloatField()
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=25)
    state = models.CharField(max_length=25)
    zip_code = models.CharField(max_length=6)
    main_photo = models.ImageField()
    photo_1 = models.ImageField()
    photo_2 = models.ImageField(blank=True)
    list_date = models.DateTimeField(default=now)
    contact_email = models.EmailField()
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "Listings"
    
    

listings/forms.py
from django import forms
from .models import Listing


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = ['title', 'condition', 'product_type', 'sale_type', 'price', 'main_photo', 'photo_1',
                  'photo_2', 'city', 'state', 'zip_code', 'contact_email', 'list_date']

listings/views.py
from django.shortcuts import render, redirect
from .models import Listing
from .forms import ListingForm

# Create your views here.
def index(request):
    return render(request, 'listings/index.html')


def greetings(request):
    return render(request,"listings/greetings.html")


def all_listings(request):
    all_listings = Listing.objects.order_by('-list_date')
    context = {'all_listings': all_listings}
    return render(request, 'listings/all_listings.html',context)


def new_listing(request):
    if request.method != "POST":
        form = ListingForm()
    else:
        form = ListingForm(request.POST, request.FILES)
        
        if form.is_valid():
            form.save()
            return redirect('listings:all_listings')
    context = {'form': form}
    return render(request,'listings/new_listings.html', context)

def details(request, detail_id):
    detail = Listing.objects.get(id=detail_id)
    context = {'detail': detail}
    return render(request,'listings/detail.html', context)

templates/listings/all_listings.html
{% extends "listings/base.html" %}

{% block content%}
    <h1>Listings</h1>

<div class="col">
    <div class="card">
        {% for listing in all_listings %}
            <p><b>Title:</b> {{ listing.title }}</p>
            <p><b>Condition:</b> {{ listing.condition }}</p>
            <p><b>Sale Type:</b> {{ listing.sale_type }}</p>
            <p><b>Price:</b> $ {{ listing.price|floatformat:2 }}</p>
            <p><b>Location:</b> {{ listing.city }}, {{ listing.state }}</p>
            <p><b>Post Date:</b> {{ listing.list_date }}</p>

            <ul>
                <a class="btn" href="{% url 'listings:detail' listing.id %}">View Listing</a>
            </ul>
        </hr>
        {% empty %}
        <h3>No Listing found. Try again.</h3>
        {% endfor %}
    </div>
</div>
{% endblock content%}

templates/listings/base.html
<nav class = "navbar">
    <a href="{% url 'listings:index' %}">BIKE FINDER</a> -
    <a href="{% url 'listings:all_listings' %}">LISTINGS</a> -
    <a href="{% url 'listings:new_listing' %}">NEW LISTING</a>
</nav>

{%block content%}

{%endblock content%}

templates/listings/detail.html
{% extends "listings/base.html" %}

{% block content %}

<div class="main">

    <h2>LISTING:</h2>

    <p><b>Title: {{ detail.title }}</p>
    <p><b>Condition:</b> {{ detail.condition }}</p>
    <p><b>Product Type:</b> {{ detail.product_type }}</p>
    <p><b>Sale Type:</b> {{ detail.sale_type }}</p>
    <p><b>Price: $</b> {{ detail.price }}</p>
    <p><b>Location:</b> {{ detail.city }}, {{ detail.state }}</p>
    <p><b>Contact Email:</b> {{ detail.contact_email }}</p>
    <p><b>Post Date:</b> {{ detail.list_date }}</p>
    <p><b>Photos:</b></p>

</div>

{% endblock content %}

templates/listings/greetings.html
<h1>GREETINGS</h1>

<h4>Welcome to my site!</h4>

templates/listings/index.html
{% extends "listings/base.html" %}

{% block content%}
    <h3>Bike Finder</h3>

    <p>This is a homepage</p>
{% endblock content%}

templates/listings/new_listings.html
{% extends "listings/base.html" %}

{% block content%}
<h1>NEW LISTGING</h1>

    <form action="{% url 'listings:new_listing' %}" method="post" enctype="multipart/form-data">
        <div class="form-group">
            {% csrf_token%}
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn">Create Listing</button>
    </form>
{% endblock content%}